import mongoose from 'mongoose';

const FormSubmissionSchema = new mongoose.Schema({
  fullName: { type: String, required: true },
  donationType: { type: String, required: true },
  totalAmount: { type: Number, required: true },
  timestamp: { type: String, default: () => new Date().toISOString() },
  email: { type: String, required: true },
  whatsapp: { type: String, required: true },
  country: { type: String },
  category: { type: String },
  quantity: { type: Number },
  donationAmount: { type: Number },
  amount: { type: Number },
  donationPurpose: { type: String },
  videoConsent: { type: String, default: 'no' },
  wakeelConsent: { type: Boolean, default: false },
  costConsent: { type: Boolean, default: false },
  fundConsent: { type: Boolean, default: false },
  currency: { type: String, default: 'USD' },
  isPaid: { type: Boolean, default: false },
  paypalOrderId: { type: String },
  paymentStatus: { type: String, default: 'pending' },
  paymentDate: { type: Date },
  requiresVideo: { type: String, default: 'no' },
  acknowledgeLogistics: { type: Boolean, default: false },
  acknowledgeRemainingFunds: { type: Boolean, default: false },
  animalCounts: { type: Object, default: {} },
  wealthAmount: { type: Number, default: 0 },
  calculatedZakah: { type: Number, default: 0 },
  nameplateText: { type: String, default: "" },
  donationComment: { type: String, default: "" },
  comments: { type: String, default: "" },
  mealCount: { type: Number, default: 0 },
  paypalTaxApplied: { type: Boolean, default: false },
  paypalTaxAmount: { type: Number, default: 0 },
  baseAmount: { type: Number, default: 0 },
  names: { type: [String], default: [] },
  wantsNameplate: { type: Boolean, default: false },
}, {
  timestamps: true,
});

export default mongoose.models.FormSubmission || mongoose.model('FormSubmission', FormSubmissionSchema);